### ISSUE TITLE
Vdr crashes in libvdr-graphlcd.so in combination with vdr-plugin-mpv

### ISSUE THREAD

**Issue by zmann182** [vdr-projects/vdr-plugin-graphlcd#8]
To avoid the crash i propose the followin patch:

--- blah/skinconfig.c.org       2024-01-19 13:31:33.178918841 +0100
+++ vdr-plugin-graphlcd-1.0.6/skinconfig.c      2024-01-19 14:11:30.757124034 +0100
@@ -625,7 +625,7 @@
         tReplayState replay = mState->GetReplayState();
         double framesPerSec =
 #if VDRVERSNUM >= 10701
-          (replay.control) ? replay.control->FramesPerSecond() : (double)DEFAULTFRAMESPERSECOND
+          (replay.control->FramesPerSecond()) ? replay.control->FramesPerSecond() : (double)DEFAULTFRAMESPERSECOND
 #else
           (double)FRAMESPERSEC
 #endif

**Comment by M-Reimer** [comment]
Can you please create a pull request from that?

**Comment by M-Reimer** [comment]
Thank you for your report and attempt to provide a fix. But as you probably see the patch is destroyed by GitHub's formatting.

Best would be if you can provide a Pull Request but maybe at least try to attach your patch here for download.

**Comment by M-Reimer** [comment]
Fixed in 1.0.7
